onboarding = false

[ui.toast]
delivery = "system"

[ui.sound]
enabled = false

[experimental]
pane_history = true
kitty_graphics = true

[keys]
prefix = "ctrl+a"

[worktrees]
directory = "~/git/worktrees"


[theme]
name = "dracula"
auto_switch = false

[ui]
show_agent_labels_on_pane_borders = false
agent_panel_sort = "priority"
