onboarding = false

[ui.toast]
delivery = "system"

[ui.sound]
enabled = false

[experimental]
pane_history = true
kitty_graphics = true

[keys]
prefix = "ctrl+space"
# General
settings = "prefix+,"
detach = "prefix+d"
reload_config = "prefix+r"
goto = "ctrl+g"
workspace_picker = ["prefix+w", "alt+w"]
split_vertical = ["prefix+|", "prefix+v"]
split_horizontal = ["prefix+-", "prefix+h"]
zoom = ["prefix+z", "alt+z"]
resize_mode = "prefix+,"
toggle_sidebar = "prefix+s"
copy_mode = "alt+enter"

# Navigation
focus_agent = "ctrl+alt+1..9"
switch_tab = "ctrl+1..9"
next_tab = "prefix+tab"
previous_tab = "prefix+shift+tab"
switch_workspace = "alt+1..9"
last_pane = "alt+tab"
previous_workspace = ["ctrl+alt+up"]
next_workspace = ["ctrl+alt+down"]

# Workspace and tab management
rename_workspace = "alt+r"
new_tab = "ctrl+t"
rename_tab = "ctrl+r"
close_pane = "prefix+w"

[worktrees]
directory = "~/git/worktrees"


[theme]
name = "nord"
auto_switch = false

[ui]
show_agent_labels_on_pane_borders = false
agent_panel_sort = "priority"


[[keys.command]]
key = "prefix+ctrl+v"
type = "popup"
command = "vi ."
description = "run vi"
width = "80%"
height = "80%"

[[keys.command]]
key = "prefix+ctrl+r"
type = "popup"
command = "ranger ."
description = "run ranger"
width = "80%"
height = "80%"
