#!/bin/env make

homebrew: 
    curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install.sh

neovim:
    brew install neovim

planuml:
    brew install plantuml

graphviz:
    brew install graphviz

cloc:
    brew install cloc

ranger:
    brew install ranger

java:
   brew cask install java 
