all: install update

update:
	cp home/cawal/.config/i3/* /home/cawal/.config/i3/

install: install-i3 install-python-modules


install-i3:
	sudo ./install-i3.sh 

install-python-modules:
	./install-python-modules.sh

