# Do not modify this file!  It was generated by 'nixos-generate-config'
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.initrd.luks.devices."luks-c68bbcad-9bcf-42a6-bc1b-6850e9742923".device = "/dev/disk/by-uuid/c68bbcad-9bcf-42a6-bc1b-6850e9742923";

  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-3e50c78f-ca7c-47c6-8792-0b6536e8d8ef";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-3e50c78f-ca7c-47c6-8792-0b6536e8d8ef".device = "/dev/disk/by-uuid/3e50c78f-ca7c-47c6-8792-0b6536e8d8ef";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/9E02-59E9";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-c68bbcad-9bcf-42a6-bc1b-6850e9742923"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
